### ISSUE TITLE
Java 7 compatibility

### ISSUE THREAD

**Issue by quinnuendo** [ivanpribela/svetovid-lib#3]
Make the library compileable and runnable using java 7.

Java 8 is out for some time now, but there is probably a lot of computer still running java 7 and since this is a beginner's tool, maybe we should target that. 

Maybe have this as a separate branch, or maybe keep the differences that are java 8 specific in a separate branch for later reintroduction.

**Comment by ivanpribela** [comment]
I agree that the library should be compatible with Java 1.7.

Project code differences between Java 1.7 and 1.8 are not yet that significant to warrant a separate branch.

**Comment by ivanpribela** [comment]
I made the necessary changes for the library to be compatible with Java 1.7.
